title: Lauren Adachi # your name (or website title) here
logo: "/images/Profile.jpg?raw=true"  # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Avionics Engineer @ Blue / EE @ Brown University
  <br><br>
  <a href="https://laurenadachi.github.io/pdf/Resume.pdf">View Resume</a> <br>
  <a href="https://www.linkedin.com/in/lauren-adachi-412a28172/">View LinkedIn Profile</a> <br>
  <a href="https://github.com/laurenadachi">View GitHub Profile</a>
  <br><br>
  <a href="https://laurenadachi.github.io">Return to Home</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
